# https://taskfile.dev
version: '3'

vars:
  ALL: ./...
  DIST: ./dist
  CMD_ROOT: ./cmd
  IMAGE: barnowlsnest/stratus
  TAG: '{{.TAG | default "latest"}}'

tasks:
  buf-build:
    desc: Build buf
    cmds:
      - buf dep update
      - buf build

  buf-gen:
    desc: Generate gRPC code from proto
    cmds:
      - buf generate

  go-build:
    deps:
      - sanity
    cmds:
      - rm -rf '{{.DIST}}'
      - mkdir -p '{{.DIST}}'
      - go build -o '{{.DIST}}' '{{.CMD_ROOT}}/app/stratus.go'

  go-fmt:
    cmds:
      - go fmt '{{.ALL}}'

  go-vet:
    cmds:
      - go vet '{{.ALL}}'

  go-test:
    cmds:
      - go test -race -cover '{{.ALL}}'

  go-lint:
    cmds:
      - golangci-lint run --fix

  sanity:
    cmds:
      - task: go-fmt
      - task: go-vet
      - task: go-lint
      - task: go-test

  clear:
    cmds:
      - rm -rf '{{.DIST}}'

  docker-build:
    deps:
      - sanity
    cmds:
      - docker build -t {{.IMAGE}}:{{.TAG}} .

  docker-push:
    deps:
      - sanity
    cmds:
      - docker push {{.IMAGE}}:{{.TAG}}

  docker-run:
    deps:
      - docker-build
    cmds:
      - docker compose up
