package storage

import (
	"bytes"
	"context"
	"sync"

	"github.com/barnowlsnest/go-logslib/v2/pkg/sharedlog"
	"github.com/barnowlsnest/go-wallib/pkg/wal"
	"github.com/barnowlsnest/stratus/internal/dedup"
)

const defaultReadBatchSize = 64

type (
	Record struct {
		// ID is the LSN assigned by the WAL. Zero on the writing path; populated on reads.
		ID uint64
		// DedupKey is the key used to deduplicate writes. It is generated by the client and must be unique per record.
		DedupKey uint64
		// Bytes is the raw payload of the record.
		Bytes []byte
	}

	Storage struct {
		maxReadBatchSize int
		wal              *wal.WAL
		dup              *dedup.Deduplicator
		subsWG           sync.WaitGroup
	}

	BatchWriteResult struct {
		DuplicatesCount uint64
		WrittenCount    uint64
		WrittenBytes    uint64
		IDs             []uint64
	}

	Option func(*Storage)
)

func WithWAL(w *wal.WAL) Option {
	return func(s *Storage) {
		s.wal = w
	}
}

func WithDeduplicator(d *dedup.Deduplicator) Option {
	return func(s *Storage) {
		s.dup = d
	}
}

func WithMaxReadBatchSize(size int) Option {
	return func(s *Storage) {
		s.maxReadBatchSize = size
	}
}

func New(opts ...Option) (*Storage, error) {
	s := new(Storage)
	for _, opt := range opts {
		opt(s)
	}

	if err := s.validate(); err != nil {
		return nil, err
	}

	s.applyDefaults()

	return s, nil
}

func (r *Record) validate() error {
	switch {
	case r == nil:
		return ErrNilRecord
	case r.DedupKey == 0:
		return ErrEmptyDedupKey
	case len(r.Bytes) == 0:
		return ErrEmptyRecord
	default:
		return nil
	}
}

// ClampRange resolves zero sentinels (from == first, to == last) and clamps an
// overlapping range to the available window. A range that falls entirely
// outside the window returns ErrOutOfBounds.
func (s *Storage) ClampRange(fromID, toID uint64) (from, to uint64, err error) {
	first, last := s.wal.FirstLSN(), s.wal.LastLSN()
	if fromID == 0 {
		fromID = first
	}
	if toID == 0 {
		toID = last
	}

	switch {
	case toID < first, fromID > last, fromID > toID:
		return 0, 0, ErrOutOfBounds
	}

	if fromID < first {
		fromID = first
	}
	if toID > last {
		toID = last
	}

	return fromID, toID, nil
}

func (s *Storage) Write(ctx context.Context, records []*Record) (*BatchWriteResult, error) {
	if len(records) == 0 {
		return nil, ErrEmptyRecord
	}

	var duplicates, written uint64
	batch := make([][]byte, 0, len(records))
	for _, record := range records {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		default:
		}

		if err := record.validate(); err != nil {
			return nil, err
		}

		if err := s.dup.Try(record.DedupKey); err != nil {
			duplicates++

			continue
		}

		batch = append(batch, record.Bytes)
		written += uint64(len(record.Bytes))
	}

	result := &BatchWriteResult{
		DuplicatesCount: duplicates,
		WrittenCount:    uint64(len(batch)),
		WrittenBytes:    written,
	}

	if len(batch) == 0 {
		return result, nil
	}

	ids, err := s.wal.AppendBatch(ctx, batch)
	if err != nil {
		return nil, err
	}

	result.IDs = ids

	return result, nil
}

func (s *Storage) Read(ctx context.Context, fromID, toID uint64) ([]*Record, error) {
	if err := s.validateRange(fromID, toID); err != nil {
		return nil, err
	}

	reader, err := s.wal.NewReader(fromID)
	if err != nil {
		return nil, err
	}
	defer func() { _ = reader.Close() }()

	batch := make([]*Record, 0, toID-fromID+1)
	for reader.Next() {
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		default:
		}

		entry, err := reader.Entry(), reader.Err()
		if err != nil {
			return nil, err
		}

		if entry.LSN > toID {
			break
		}

		chunk := &Record{
			ID:    entry.LSN,
			Bytes: bytes.Clone(entry.Payload),
		}

		batch = append(batch, chunk)
	}

	return batch, nil
}

func (s *Storage) Del(ctx context.Context, upToID uint64) error {
	switch {
	case upToID == 0:
		return ErrOutOfBounds
	case s.wal.FirstLSN() > upToID:
		return ErrOutOfBounds
	case s.wal.LastLSN() < upToID:
		return ErrOutOfBounds
	}

	return s.wal.CutOffsetContext(ctx, upToID)
}

func (s *Storage) Subscribe(ctx context.Context, fromID uint64, buffer int) (records <-chan *Record, err error) {
	if buffer <= 0 {
		buffer = 1
	}

	f, err := s.wal.Follower(fromID, wal.WithFollow())
	if err != nil {
		closedCh := make(chan *Record)
		close(closedCh)
		return closedCh, err
	}

	recordsCh := make(chan *Record, buffer)
	s.subsWG.Go(func() {
		defer close(recordsCh)
		for entry := range f.RecordsChan(ctx) {
			recordsCh <- &Record{ID: entry.LSN, Bytes: bytes.Clone(entry.Payload)}
		}

		if errClose := f.Close(); errClose != nil {
			sharedlog.Error(errClose)
		}
		if errFollower := f.Err(); errFollower != nil {
			sharedlog.Error(errFollower)
		}
	})

	return recordsCh, nil
}

func (s *Storage) Range() (first, last uint64) {
	return s.wal.FirstLSN(), s.wal.LastLSN()
}

func (s *Storage) WaitSubscribersDone(ctx context.Context) {
	done := make(chan struct{})
	go func() {
		defer close(done)
		s.subsWG.Wait()
	}()

	select {
	case <-ctx.Done():
		return
	case <-done:
		return
	}
}

func (s *Storage) validate() error {
	switch {
	case s == nil:
		return ErrNilStorage
	case s.wal == nil:
		return ErrNilOption
	case s.dup == nil:
		return ErrNilOption
	default:
		return nil
	}
}

func (s *Storage) applyDefaults() {
	if s.maxReadBatchSize == 0 {
		s.maxReadBatchSize = defaultReadBatchSize
	}
}

func (s *Storage) validateRange(fromID, toID uint64) error {
	switch {
	case fromID == 0, toID == 0:
		return ErrOutOfBounds
	case fromID > toID:
		return ErrOutOfBounds
	case int(toID-fromID+1) > s.maxReadBatchSize:
		return ErrTooLongRangeToRead
	case s.wal.LastLSN() < fromID:
		return ErrOutOfBounds
	case s.wal.FirstLSN() > toID:
		return ErrOutOfBounds
	}

	return nil
}
