// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: stratus/v1/stratus.proto

package stratusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStreamInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *StreamInfo            `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamInfoResponse) Reset() {
	*x = GetStreamInfoResponse{}
	mi := &file_stratus_v1_stratus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamInfoResponse) ProtoMessage() {}

func (x *GetStreamInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stratus_v1_stratus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamInfoResponse.ProtoReflect.Descriptor instead.
func (*GetStreamInfoResponse) Descriptor() ([]byte, []int) {
	return file_stratus_v1_stratus_proto_rawDescGZIP(), []int{0}
}

func (x *GetStreamInfoResponse) GetInfo() *StreamInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type StreamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         *Range                 `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	CachedRecords uint64                 `protobuf:"varint,2,opt,name=cached_records,json=cachedRecords,proto3" json:"cached_records,omitempty"`
	FsRecords     uint64                 `protobuf:"varint,3,opt,name=fs_records,json=fsRecords,proto3" json:"fs_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInfo) Reset() {
	*x = StreamInfo{}
	mi := &file_stratus_v1_stratus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInfo) ProtoMessage() {}

func (x *StreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stratus_v1_stratus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInfo.ProtoReflect.Descriptor instead.
func (*StreamInfo) Descriptor() ([]byte, []int) {
	return file_stratus_v1_stratus_proto_rawDescGZIP(), []int{1}
}

func (x *StreamInfo) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *StreamInfo) GetCachedRecords() uint64 {
	if x != nil {
		return x.CachedRecords
	}
	return 0
}

func (x *StreamInfo) GetFsRecords() uint64 {
	if x != nil {
		return x.FsRecords
	}
	return 0
}

type ReCacheResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Range         *Range                 `protobuf:"bytes,1,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReCacheResponse) Reset() {
	*x = ReCacheResponse{}
	mi := &file_stratus_v1_stratus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReCacheResponse) ProtoMessage() {}

func (x *ReCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stratus_v1_stratus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReCacheResponse.ProtoReflect.Descriptor instead.
func (*ReCacheResponse) Descriptor() ([]byte, []int) {
	return file_stratus_v1_stratus_proto_rawDescGZIP(), []int{2}
}

func (x *ReCacheResponse) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

type InputRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DedupKey      uint64                 `protobuf:"varint,1,opt,name=dedup_key,json=dedupKey,proto3" json:"dedup_key,omitempty"`
	RawData       []byte                 `protobuf:"bytes,16,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputRecord) Reset() {
	*x = InputRecord{}
	mi := &file_stratus_v1_stratus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputRecord) ProtoMessage() {}

func (x *InputRecord) ProtoReflect() protoreflect.Message {
	mi := &file_stratus_v1_stratus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputRecord.ProtoReflect.Descriptor instead.
func (*InputRecord) Descriptor() ([]byte, []int) {
	return file_stratus_v1_stratus_proto_rawDescGZIP(), []int{3}
}

func (x *InputRecord) GetDedupKey() uint64 {
	if x != nil {
		return x.DedupKey
	}
	return 0
}

func (x *InputRecord) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Range) Reset() {
	*x = Range{}
	mi := &file_stratus_v1_stratus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_stratus_v1_stratus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_stratus_v1_stratus_proto_rawDescGZIP(), []int{4}
}

func (x *Range) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Range) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

type OutputRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RawData       []byte                 `protobuf:"bytes,16,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputRecord) Reset() {
	*x = OutputRecord{}
	mi := &file_stratus_v1_stratus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputRecord) ProtoMessage() {}

func (x *OutputRecord) ProtoReflect() protoreflect.Message {
	mi := &file_stratus_v1_stratus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputRecord.ProtoReflect.Descriptor instead.
func (*OutputRecord) Descriptor() ([]byte, []int) {
	return file_stratus_v1_stratus_proto_rawDescGZIP(), []int{5}
}

func (x *OutputRecord) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OutputRecord) GetRawData() []byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type ReadOffsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartId       uint64                 `protobuf:"varint,1,opt,name=start_id,json=startId,proto3" json:"start_id,omitempty"`
	MaxRecords    uint64                 `protobuf:"varint,2,opt,name=max_records,json=maxRecords,proto3" json:"max_records,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOffsetRequest) Reset() {
	*x = ReadOffsetRequest{}
	mi := &file_stratus_v1_stratus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOffsetRequest) ProtoMessage() {}

func (x *ReadOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stratus_v1_stratus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOffsetRequest.ProtoReflect.Descriptor instead.
func (*ReadOffsetRequest) Descriptor() ([]byte, []int) {
	return file_stratus_v1_stratus_proto_rawDescGZIP(), []int{6}
}

func (x *ReadOffsetRequest) GetStartId() uint64 {
	if x != nil {
		return x.StartId
	}
	return 0
}

func (x *ReadOffsetRequest) GetMaxRecords() uint64 {
	if x != nil {
		return x.MaxRecords
	}
	return 0
}

func (x *ReadOffsetRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type ReadRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartId       uint64                 `protobuf:"varint,1,opt,name=start_id,json=startId,proto3" json:"start_id,omitempty"`
	EndId         uint64                 `protobuf:"varint,2,opt,name=end_id,json=endId,proto3" json:"end_id,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRangeRequest) Reset() {
	*x = ReadRangeRequest{}
	mi := &file_stratus_v1_stratus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRangeRequest) ProtoMessage() {}

func (x *ReadRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stratus_v1_stratus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRangeRequest.ProtoReflect.Descriptor instead.
func (*ReadRangeRequest) Descriptor() ([]byte, []int) {
	return file_stratus_v1_stratus_proto_rawDescGZIP(), []int{7}
}

func (x *ReadRangeRequest) GetStartId() uint64 {
	if x != nil {
		return x.StartId
	}
	return 0
}

func (x *ReadRangeRequest) GetEndId() uint64 {
	if x != nil {
		return x.EndId
	}
	return 0
}

func (x *ReadRangeRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*InputRecord         `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_stratus_v1_stratus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stratus_v1_stratus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_stratus_v1_stratus_proto_rawDescGZIP(), []int{8}
}

func (x *AddRequest) GetRecords() []*InputRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type AddResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AddedRecords     *Range                 `protobuf:"bytes,1,opt,name=added_records,json=addedRecords,proto3" json:"added_records,omitempty"`
	StreamRecords    *Range                 `protobuf:"bytes,2,opt,name=stream_records,json=streamRecords,proto3" json:"stream_records,omitempty"`
	DuplicateRecords uint64                 `protobuf:"varint,3,opt,name=duplicate_records,json=duplicateRecords,proto3" json:"duplicate_records,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_stratus_v1_stratus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stratus_v1_stratus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_stratus_v1_stratus_proto_rawDescGZIP(), []int{9}
}

func (x *AddResponse) GetAddedRecords() *Range {
	if x != nil {
		return x.AddedRecords
	}
	return nil
}

func (x *AddResponse) GetStreamRecords() *Range {
	if x != nil {
		return x.StreamRecords
	}
	return nil
}

func (x *AddResponse) GetDuplicateRecords() uint64 {
	if x != nil {
		return x.DuplicateRecords
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*OutputRecord        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_stratus_v1_stratus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stratus_v1_stratus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_stratus_v1_stratus_proto_rawDescGZIP(), []int{10}
}

func (x *ReadResponse) GetRecords() []*OutputRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EndId         uint64                 `protobuf:"varint,1,opt,name=end_id,json=endId,proto3" json:"end_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_stratus_v1_stratus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stratus_v1_stratus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_stratus_v1_stratus_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRequest) GetEndId() uint64 {
	if x != nil {
		return x.EndId
	}
	return 0
}

type DeleteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeletedRecords *Range                 `protobuf:"bytes,1,opt,name=deleted_records,json=deletedRecords,proto3" json:"deleted_records,omitempty"`
	StreamRecords  *Range                 `protobuf:"bytes,2,opt,name=stream_records,json=streamRecords,proto3" json:"stream_records,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_stratus_v1_stratus_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stratus_v1_stratus_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_stratus_v1_stratus_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteResponse) GetDeletedRecords() *Range {
	if x != nil {
		return x.DeletedRecords
	}
	return nil
}

func (x *DeleteResponse) GetStreamRecords() *Range {
	if x != nil {
		return x.StreamRecords
	}
	return nil
}

var File_stratus_v1_stratus_proto protoreflect.FileDescriptor

const file_stratus_v1_stratus_proto_rawDesc = "" +
	"\n" +
	"\x18stratus/v1/stratus.proto\x12\n" +
	"stratus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\"C\n" +
	"\x15GetStreamInfoResponse\x12*\n" +
	"\x04info\x18\x01 \x01(\v2\x16.stratus.v1.StreamInfoR\x04info\"{\n" +
	"\n" +
	"StreamInfo\x12'\n" +
	"\x05range\x18\x01 \x01(\v2\x11.stratus.v1.RangeR\x05range\x12%\n" +
	"\x0ecached_records\x18\x02 \x01(\x04R\rcachedRecords\x12\x1d\n" +
	"\n" +
	"fs_records\x18\x03 \x01(\x04R\tfsRecords\":\n" +
	"\x0fReCacheResponse\x12'\n" +
	"\x05range\x18\x01 \x01(\v2\x11.stratus.v1.RangeR\x05range\"K\n" +
	"\vInputRecord\x12\x1b\n" +
	"\tdedup_key\x18\x01 \x01(\x04R\bdedupKey\x12\x19\n" +
	"\braw_data\x18\x10 \x01(\fR\arawDataJ\x04\b\x02\x10\x10\"/\n" +
	"\x05Range\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x04R\x03end\"?\n" +
	"\fOutputRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x19\n" +
	"\braw_data\x18\x10 \x01(\fR\arawDataJ\x04\b\x02\x10\x10\"\x84\x01\n" +
	"\x11ReadOffsetRequest\x12\x19\n" +
	"\bstart_id\x18\x01 \x01(\x04R\astartId\x12\x1f\n" +
	"\vmax_records\x18\x02 \x01(\x04R\n" +
	"maxRecords\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"y\n" +
	"\x10ReadRangeRequest\x12\x19\n" +
	"\bstart_id\x18\x01 \x01(\x04R\astartId\x12\x15\n" +
	"\x06end_id\x18\x02 \x01(\x04R\x05endId\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"?\n" +
	"\n" +
	"AddRequest\x121\n" +
	"\arecords\x18\x01 \x03(\v2\x17.stratus.v1.InputRecordR\arecords\"\xac\x01\n" +
	"\vAddResponse\x126\n" +
	"\radded_records\x18\x01 \x01(\v2\x11.stratus.v1.RangeR\faddedRecords\x128\n" +
	"\x0estream_records\x18\x02 \x01(\v2\x11.stratus.v1.RangeR\rstreamRecords\x12+\n" +
	"\x11duplicate_records\x18\x03 \x01(\x04R\x10duplicateRecords\"B\n" +
	"\fReadResponse\x122\n" +
	"\arecords\x18\x01 \x03(\v2\x18.stratus.v1.OutputRecordR\arecords\"&\n" +
	"\rDeleteRequest\x12\x15\n" +
	"\x06end_id\x18\x01 \x01(\x04R\x05endId\"\x86\x01\n" +
	"\x0eDeleteResponse\x12:\n" +
	"\x0fdeleted_records\x18\x01 \x01(\v2\x11.stratus.v1.RangeR\x0edeletedRecords\x128\n" +
	"\x0estream_records\x18\x02 \x01(\v2\x11.stratus.v1.RangeR\rstreamRecords2\xa2\x03\n" +
	"\rStreamService\x12?\n" +
	"\x06Delete\x12\x19.stratus.v1.DeleteRequest\x1a\x1a.stratus.v1.DeleteResponse\x126\n" +
	"\x03Add\x12\x16.stratus.v1.AddRequest\x1a\x17.stratus.v1.AddResponse\x12C\n" +
	"\tReadRange\x12\x1c.stratus.v1.ReadRangeRequest\x1a\x18.stratus.v1.ReadResponse\x12>\n" +
	"\aReCache\x12\x16.google.protobuf.Empty\x1a\x1b.stratus.v1.ReCacheResponse\x12J\n" +
	"\rGetStreamInfo\x12\x16.google.protobuf.Empty\x1a!.stratus.v1.GetStreamInfoResponse\x12G\n" +
	"\n" +
	"ReadOffset\x12\x1d.stratus.v1.ReadOffsetRequest\x1a\x18.stratus.v1.ReadResponse0\x01B7Z5github.com/barnowlsnest/stratus/api/grpc/v1;stratusv1b\x06proto3"

var (
	file_stratus_v1_stratus_proto_rawDescOnce sync.Once
	file_stratus_v1_stratus_proto_rawDescData []byte
)

func file_stratus_v1_stratus_proto_rawDescGZIP() []byte {
	file_stratus_v1_stratus_proto_rawDescOnce.Do(func() {
		file_stratus_v1_stratus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stratus_v1_stratus_proto_rawDesc), len(file_stratus_v1_stratus_proto_rawDesc)))
	})
	return file_stratus_v1_stratus_proto_rawDescData
}

var file_stratus_v1_stratus_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_stratus_v1_stratus_proto_goTypes = []any{
	(*GetStreamInfoResponse)(nil), // 0: stratus.v1.GetStreamInfoResponse
	(*StreamInfo)(nil),            // 1: stratus.v1.StreamInfo
	(*ReCacheResponse)(nil),       // 2: stratus.v1.ReCacheResponse
	(*InputRecord)(nil),           // 3: stratus.v1.InputRecord
	(*Range)(nil),                 // 4: stratus.v1.Range
	(*OutputRecord)(nil),          // 5: stratus.v1.OutputRecord
	(*ReadOffsetRequest)(nil),     // 6: stratus.v1.ReadOffsetRequest
	(*ReadRangeRequest)(nil),      // 7: stratus.v1.ReadRangeRequest
	(*AddRequest)(nil),            // 8: stratus.v1.AddRequest
	(*AddResponse)(nil),           // 9: stratus.v1.AddResponse
	(*ReadResponse)(nil),          // 10: stratus.v1.ReadResponse
	(*DeleteRequest)(nil),         // 11: stratus.v1.DeleteRequest
	(*DeleteResponse)(nil),        // 12: stratus.v1.DeleteResponse
	(*durationpb.Duration)(nil),   // 13: google.protobuf.Duration
	(*emptypb.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_stratus_v1_stratus_proto_depIdxs = []int32{
	1,  // 0: stratus.v1.GetStreamInfoResponse.info:type_name -> stratus.v1.StreamInfo
	4,  // 1: stratus.v1.StreamInfo.range:type_name -> stratus.v1.Range
	4,  // 2: stratus.v1.ReCacheResponse.range:type_name -> stratus.v1.Range
	13, // 3: stratus.v1.ReadOffsetRequest.timeout:type_name -> google.protobuf.Duration
	13, // 4: stratus.v1.ReadRangeRequest.timeout:type_name -> google.protobuf.Duration
	3,  // 5: stratus.v1.AddRequest.records:type_name -> stratus.v1.InputRecord
	4,  // 6: stratus.v1.AddResponse.added_records:type_name -> stratus.v1.Range
	4,  // 7: stratus.v1.AddResponse.stream_records:type_name -> stratus.v1.Range
	5,  // 8: stratus.v1.ReadResponse.records:type_name -> stratus.v1.OutputRecord
	4,  // 9: stratus.v1.DeleteResponse.deleted_records:type_name -> stratus.v1.Range
	4,  // 10: stratus.v1.DeleteResponse.stream_records:type_name -> stratus.v1.Range
	11, // 11: stratus.v1.StreamService.Delete:input_type -> stratus.v1.DeleteRequest
	8,  // 12: stratus.v1.StreamService.Add:input_type -> stratus.v1.AddRequest
	7,  // 13: stratus.v1.StreamService.ReadRange:input_type -> stratus.v1.ReadRangeRequest
	14, // 14: stratus.v1.StreamService.ReCache:input_type -> google.protobuf.Empty
	14, // 15: stratus.v1.StreamService.GetStreamInfo:input_type -> google.protobuf.Empty
	6,  // 16: stratus.v1.StreamService.ReadOffset:input_type -> stratus.v1.ReadOffsetRequest
	12, // 17: stratus.v1.StreamService.Delete:output_type -> stratus.v1.DeleteResponse
	9,  // 18: stratus.v1.StreamService.Add:output_type -> stratus.v1.AddResponse
	10, // 19: stratus.v1.StreamService.ReadRange:output_type -> stratus.v1.ReadResponse
	2,  // 20: stratus.v1.StreamService.ReCache:output_type -> stratus.v1.ReCacheResponse
	0,  // 21: stratus.v1.StreamService.GetStreamInfo:output_type -> stratus.v1.GetStreamInfoResponse
	10, // 22: stratus.v1.StreamService.ReadOffset:output_type -> stratus.v1.ReadResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_stratus_v1_stratus_proto_init() }
func file_stratus_v1_stratus_proto_init() {
	if File_stratus_v1_stratus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stratus_v1_stratus_proto_rawDesc), len(file_stratus_v1_stratus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stratus_v1_stratus_proto_goTypes,
		DependencyIndexes: file_stratus_v1_stratus_proto_depIdxs,
		MessageInfos:      file_stratus_v1_stratus_proto_msgTypes,
	}.Build()
	File_stratus_v1_stratus_proto = out.File
	file_stratus_v1_stratus_proto_goTypes = nil
	file_stratus_v1_stratus_proto_depIdxs = nil
}
